---
# general
proxy_compose_retries: 5
proxy_compose_retries_delay_sec: 10

proxy_network_name: "proxy"
proxy_compose_project: "proxy"

# 3x-ui
proxy_ui_version: v1.7.9

# caddy
proxy_caddy_version: 2.8-alpine
