---
- name: Enable nftables service
  become: true
  ansible.builtin.systemd:
    name: nftables.service
    enabled: true

- name: Configure nftables ingress rules
  become: true
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nftables
